name: xrp_tracker
description: A Flutter app that tracks XRP to MYR value.

# Other settings...

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.2.1
  intl: ^0.19.0
  google_fonts: ^6.1.0  # 👈 Add this line here

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1  # ✅ Add this line


flutter:
  uses-material-design: true

  assets:
    - assets/images/background.jpg
    - assets/images/xrp_icon.png
